# Generated by Django 4.2.3 on 2023-07-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
