# Generated by Django 4.2.3 on 2023-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_link_short_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
